<a href="https://colab.research.google.com/github/smiledinisa/data_python_analysis/blob/master/pandas001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第五章 pandas 入门

![替代文字](https://img-blog.csdnimg.cn/20200807151248699.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2dhb2N1aTg4Mw==,size_16,color_FFFFFF,t_70)

In [2]:
from pandas import Series, DataFrame
import pandas as pd


## pandas的数据结构介绍

### Series
由一组数据（numpy）以及一组与之相关的数据标签组成。

In [3]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4,7,5,3], index=['a', 'b', 'c', 'd'])

In [7]:
obj2

a    4
b    7
c    5
d    3
dtype: int64

In [10]:
obj2['d']

3

In [13]:
# 字典的转换。
sdata = {'ohi':3500, 'texa':7100, 'orgen':1900, 'utah':4000}
obj3 = Series(sdata)

In [14]:
obj3

ohi      3500
texa     7100
orgen    1900
utah     4000
dtype: int64

In [17]:
states = ['aiaang','ohi',  'orgen', 'utah']
obj4 = Series(sdata, index=states)

In [18]:
obj4

aiaang       NaN
ohi       3500.0
orgen     1900.0
utah      4000.0
dtype: float64

In [19]:
# NaN表示缺失。
# isnull和notnull 来检测缺失数据。


In [20]:
pd.isnull(obj4)

aiaang     True
ohi       False
orgen     False
utah      False
dtype: bool

In [21]:
pd.notnull(obj4)

aiaang    False
ohi        True
orgen      True
utah       True
dtype: bool

In [22]:
obj4.isnull()

aiaang     True
ohi       False
orgen     False
utah      False
dtype: bool

以上三种方法都是可以的。

In [23]:
obj3

ohi      3500
texa     7100
orgen    1900
utah     4000
dtype: int64

In [24]:
obj4

aiaang       NaN
ohi       3500.0
orgen     1900.0
utah      4000.0
dtype: float64

In [25]:
obj3+obj4

aiaang       NaN
ohi       7000.0
orgen     3800.0
texa         NaN
utah      8000.0
dtype: float64

Series 对象的name 属性。


In [26]:
obj4.name = 'population'
obj4.index.name = 'state'

In [27]:
obj4

state
aiaang       NaN
ohi       3500.0
orgen     1900.0
utah      4000.0
Name: population, dtype: float64

### DataFrame

In [3]:
import numpy as np
import pandas as pd
from pandas import Series
from pandas import DataFrame
# 传入由等长列表组成的字典，来构建DataFrame
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [4]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [6]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [7]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [8]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [9]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [11]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [12]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [13]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [14]:
# the rows also can be retrieved by position or name. use attribute ..loc
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [16]:
# empyt colum 'debt' can be assigned
frame2['debt'] = 100
frame2

year   state  pop  debt
one    2000    Ohio  1.5   100
two    2001    Ohio  1.7   100
three  2002    Ohio  3.6   100
four   2001  Nevada  2.4   100
five   2002  Nevada  2.9   100

In [20]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [22]:
# note the length must match.
# if use a Series assign a colum , the index must be realigned exactly to DataFrame's

# if not , inserting some missing values in any holes. with NaN

val = pd.Series([1.5, 2.5, -3.6], index=['one', 'three', 'five'])
frame2['debt'] = val

frame2

# u can see the result like this:

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   2.5
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -3.6

In [27]:
 # del keyword. and creat a new colum
 frame2['eastern'] = frame2.state == 'Ohio'
 frame2
 # note: new colums can not be created by frame2.estern

year   state  pop  debt  eastern
one    2000    Ohio  1.5   1.5     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   2.5     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9  -3.6    False

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [31]:
del frame2['eastern']

In [33]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [35]:
# note that delete a column aslo can not be use "del frame2.xxx"
# its not copy, its only view on the data



In [36]:
#anothe common form of data is nested dict of dicts:

pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
       

In [37]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [42]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [39]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [40]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [43]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [44]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [45]:
frame3.values # two dimensional ndarray.

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   2.5
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -3.6

In [47]:
frame2.values

array([[2000, 'Ohio', 1.5, 1.5],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, 2.5],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -3.6]], dtype=object)

所有可能传给DataFrame的值：

![替代文字](https://img-blog.csdnimg.cn/2020080722105763.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2dhb2N1aTg4Mw==,size_16,color_FFFFFF,t_70)

### Index Objects 索引对象